/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_study_javaCore_jni_NativeEncryptUtils */

#ifndef _Included_com_me_study_javaCore_jni_NativeEncryptUtils
#define _Included_com_me_study_javaCore_jni_NativeEncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_study_javaCore_jni_NativeEncryptUtils
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_me_study_javaCore_jni_NativeEncryptUtils_decrypt
  (JNIEnv *env, jclass clazz, jbyteArray inputArray);

#ifdef __cplusplus
}
#endif
#endif
