name: Build SO

on:
# 手动触发
  workflow_dispatch:
# push 或者 合并到 master 时触发
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build-linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libstdc++6

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        cd ..
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

    - name: Install libcurl
      run: |
        cd ${{ env.VCPKG_ROOT }}
        ./vcpkg install --triplet x64-linux curl
        cd ..

    - name: Configure CMake and Build with CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config Release

    - name: Upload SO
      uses: actions/upload-artifact@v4
      with:
        name: my-so
        path: build/*.so
