name: Build DLL and SO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.3

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: my-dll
        path: build/Release/*.dll

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.3

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Upload SO
      uses: actions/upload-artifact@v4
      with:
        name: my-so
        path: build/*.so
