name: Build Windows DLL

on:
# 手动触发
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
# push 或者 合并到 master 时触发
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        cd ..
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $env:GITHUB_ENV

    - name: Install libcurl
      run: |
        cd ${{ env.VCPKG_ROOT }}
        ./vcpkg install curl:x64-windows
        cd ..

    - name: Configure CMake and Build with CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config Release

    - name: Setup Debug Session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: my-dll
        path: build/Release/*.dll
